### ISSUE TITLE
sugestion: Add support for rclone to Disbox

### ISSUE THREAD

**Issue by jollran2005** [tris203/disftp#22]
Hello,

I would like to know if it in any way would be possible to add support for Disbox to rclone. A user in the github for disbox recommended your project.

I asked in the github from rclone and received the following response: https://github.com/rclone/rclone/issues/7477#issuecomment-1837080097

Here is the link to rclone's github if anyone wants to look into it:
https://github.com/rclone/rclone

Thanks!

**Comment by tris203** [comment]
Probably the most robust way is to add it as a new backend in rclone direct
Although rclone is written in go, so its not something I can directly help with.

You might be able to get away with setting this up and linking rclone to a FTP server provided through this. But its not something I use directly, so you would have to set it up, test and see what happen

**Comment by jollran2005** [comment]
> Probably the most robust way is to add it as a new backend in rclone direct Although rclone is written in go, so its not something I can directly help with.
> 
> You might be able to get away with setting this up and linking rclone to a FTP server provided through this. But its not something I use directly, so you would have to set it up, test and see what happen

Thanks, I'm no programmer myself but I'll try looking into it.
