### ISSUE TITLE
Can't figure out how to run index.js

### ISSUE THREAD

**Issue by jollran2005** [tris203/disftp#23]
I have completed all steps up until run index.js but I can't figure it out. I navigated to disftp/dist and tried running node index.js but I get the same result as when running npm run start. What do I do next?

**Comment by tris203** [comment]
What happens when you ```npm run start```

**Comment by jollran2005** [comment]
I get:
Ftp server is starting...
Listening on 0.0.0.0:21 with pasv on undefined

As I understand it, this means it is running correctly, so what is the next step?

**Comment by tris203** [comment]
Yeah that's running. So use an FTP client (WinSCP recommended) and connect to localhost using the credentials as per the README

**Comment by jollran2005** [comment]
Thank you, I got it to work!
