### ISSUE TITLE
while i uploading the app says no such file or directory and disconnects me

### ISSUE THREAD

**Issue by furllmm** [tris203/disftp#24]
log is here 
Error: ENOENT: no such file or directory, open 'E:\disbox\dist\tmp\toucan.7z'
Emitted 'error' event on WriteStream instance at:
    at emitErrorNT (node:internal/streams/destroy:151:8)
    at emitErrorCloseNT (node:internal/streams/destroy:116:3)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
  errno: -4058,
  code: 'ENOENT',
  syscall: 'open',
  path: 'E:\\disbox\\dist\\tmp\\toucan.7z'
}

**Comment by tris203** [comment]
What size is the file? and what FTP client are you using?

**Comment by furllmm** [comment]
29 KB i tried few byte of txt file same problem too

**Comment by furllmm** [comment]
winscp

**Comment by furllmm** [comment]
also happenes same to 2MB file too

**Comment by tris203** [comment]
The tmp path is meant to be at the level above

Individual systems are hard to debug

I would suggest the docker container

**Comment by tris203** [comment]
Just another thought. Are you running npm start from in the dist folder?

Try running it from the main project folder

**Comment by furllmm** [comment]
Try running it from the main project folder worked
but i cannot upload folders

**Comment by tris203** [comment]
Yeah. Uploading a folder isn't supported yet I don't think
